# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'SuperNovaZJX440'

steps:
- task: ostorlab-azure-security-scanner@1
  inputs:
    apiKey: 'QXsyTePs.gLgVsMbYAyHraLjSaRJbIYfueJrWQpGk'
    filepath: 'a'
    platform: 'android'
    artifactsDir: '$(build.artifactStagingDirectory)/../Ostorlab_insecure_app.apk'
    title: 'Some title'
